name: SkySchems
version: 1.0
main: me.jolikki.skyschems.SkySchems
api-version: 1.16
author: jolikki

commands:
  skyschems:
    description: Preview and paste schematics
    usage: /skyschems <help|preview|paste|clear|reload>
    aliases:
      - ss
      - schem
    permission: skyschems.command.use

permissions:
  skyschems.command.use:
    description: Allows using SkySchems commands
    default: op
  skyschems.command.reload:
    description: Allows reloading SkySchems config
    default: op
